airlines = {
              'NK': 'Spirit Airlines',
              'F9': 'Frontier Airlines',
              'B6': 'JetBlue',
              'US': 'US Airways',
              'AS': 'Alaska Airlines',
              'VX': 'Virgin America',
              'HA': 'Hawaiian Airlines',
              'UA': 'United Airlines',
              'AF': 'Air France',
              'NQ': 'Air Japan',
              'NH': 'All Nippon Airways',
              'AB': 'Air Berlin',
              'AI': 'Air India',
              'JM': 'Air Jamaica',
              'AC': 'Air Canada',
              'EI': 'Aer Lingus',
              'AR': 'Aerolineas Argentinas',
              'AM': 'Aeromexico',
              'CA': 'Air China',
              'AA': 'American Airlines',
              'KL': 'Royal Dutch Airlines',
              'VS': 'Virgin Atlantic',
              'BA': 'British Airways',
              'JL': 'Japan Airlines',
              'MH': 'Malaysia Airlines',
              'EY': 'Etihad Airways',
              'WS': 'WestJet',
              'AT': 'Royal Air Maroc',
              'TP': 'TAP Portugal',
              'TK': 'Turkish Airlines',
              'IB': 'Iberia',
              'SA': 'South African Airways',
              'DL': 'Delta Airlines',
              'LX': 'Swiss Airlines',
              'SK': 'Scandinavian Airlines',
              'EK': 'Emirates Airlines',
              'CX': 'Cathay Pacific,',
              'CI': 'China Airlines',
              'DY': 'Norwegian Air',
              'LA': 'LAN Airlines',
              'MU': 'China Eastern Airlines',
              'CZ': 'China Southern Airlines',
              'AY': 'Finnair',
              'VN': 'Vietnam Airlines',
              'LY': 'El Al Israel Airlines',
              'AZ': 'Alitalia',
              'JM': 'Air Jamaica',
              'NH': 'All Nippon Airways',
              'JL': 'Japan Airlines',
              'RJ': 'Royal Jordanian Airlines',
              'KW': 'Korean Air',
              'AM': 'Aeromexico',
              'MX': 'Mexicana Airlines',
              'NZ': 'Air New Zealand',
              'PL': 'Aero Peru',
              'PR': 'Philippine Air Lines',
              'LO': 'Lot Polish Airlines',
              'SU': 'Aeroflot',
              'SQ': 'Singapore Airlines',
              'IB': 'Iberia',
              'TG': 'Thai Airways',
              'LH': 'Lufthansa',
              'OG': 'Go Fly Ltd.',
              'OS': 'Austrian Airlines',
              'QF': 'Qantas Airlines',
              'AQ': 'Aloha Air',
              'HP': 'America West Airlines',
              'CO': 'Continental Airlines',
              'YX': 'Midwest Express',
              'NW': 'Northwest Airlines',
              'WN': 'Southwest Airlines',
              'FL': 'AirTran',
              'VA': 'Virgin Australia',
              'BR': 'EVA Airlines',
              'HU': 'Hainian Airlines',
              'SY': 'Sun Country Airlines',
              'QR': 'Qatar Airways',
              'KE': 'Korean Air',
              'CM': 'Copa Airlines',
              'FM': 'Shanghai Airlines',
              'AV': 'Avianca Brazil Airlines',
              'JJ': 'TAM Airlines',
              '4M': 'LAN Argentina Airlines',
              'OZ': 'Asiana Airlines'
              }











cities = {  
                            "ATL": "Atlanta, Georgia",
                            "BOS": "Boston, Massachusetts",
                            "ORD": "Chicago, Illinois",
                            "DFW": "Dallas, Texas ",
                            "DEN": "Denver, Colorado",
                            "LAS": "Las Vegas, Nevada",
                            "LAX": "Los Angeles, California",
                            "OGG": "Maui, Hawaii",
                            "MIA": "Miami, Florida",
                            "JFK": "New York, New York",
                            "PHX": "Phoenix, Arizona",
                            "SFO": "San Francisco, California",
                            "SEA": "Seattle, Washington ",
                            "IAD": "Washington D.C.",
                            "EZE": "Buenos Aires, Argentina",
                            "SYD": "Sydney, Australia",
                            "GIG": "Rio de Janeiro, Brazil",
                            "PEK": "Beijing, China",
                            "CPH": "Cophenhagen, Denmark",
                            "LHR": "London, England",
                            "CDG": "Paris, France",
                            "TXL": "Berlin, Germany",
                            "DUB": "Dublin, Ireland",
                            "FCO": "Rome, Italy",
                            "MBJ": "Montego Bay, Jamaica",
                            "HND": "Tokyo, Japan",
                            "KUL": "Kuala Lumpur, Malaysia",
                            "CUN": "Cancun, Mexico",
                            "YUL": "Montreal, Quebec, Canada",
                            "RAK": "Marrakech, Morocco",
                            "AMS": "Amsterdam, The Netherlands",
                            "LIS": "Lisbon, Portugal",
                            "SJU": "San Juan, Puerto Rico",
                            "MAD": "Madrid, Spain",
                            "CPT": "Cape Town, South Africa",
                            "YYZ": "Toronto, Ontario, Canada",
                            "IST": "Istanbul, Turkey",
                            "DXB": "Dubai, United Arab Emirates",
                            "YVR": "Vancouver, British Columbia, Canada",
                            "SGN": "Ho Chi Minh City, Vietnam",
                            "CLT": "Charlotte, North Carolina",
                            "PHL": "Philadelphia, Pennsylvania",
                            "DAL": "Dallas, Texas",
                            "DCA": "Washington D.C."
                            }

airports = {
                            "ATL": "Hartsfield-Jackson Atlanta International Airport",
                            "BOS": "Boston Logan International Airport",
                            "ORD": "Chicago O'Hare International",
                            "DFW": "Dallas/Fort Worth International Airport",
                            "DEN": "Denver International Airport",
                            "LAS": "Las Vegas McCarran International Airport",
                            "LAX": "Los Angeles International Airport",
                            "OGG": "Kahului Airport",
                            "MIA": "Miami International Airport",
                            "JFK": "John F. Kennedy International Airport",
                            "PHX": "Phoenix Sky Harbor International Airport",
                            "SFO": "San Francisco International Airport",
                            "SEA": "Seattle-Tacoma International Airport",
                            "IAD": "Washington Dulles International Airport",
                            "EZE": "Buenos Aires Ezeiza International Airport",
                            "SYD": "Sydney Airport",
                            "GIG": "Rio de Janeiro International Airport",
                            "PEK": "Beijing Capital International Airport",
                            "CPH": "Copenhagen Airport",
                            "LHR": "London Heathrow Airport",
                            "CDG": "Paris Charles De Gaulle Airport",
                            "TXL": "Berlin Tegel Airport",
                            "DUB": "Dublin Airport",
                            "FCO": "Leonardo da Vinci International Airport",
                            "MBJ": "Sangster International Airport",
                            "HND": "Haneda Airport",
                            "KUL": "Kuala Lumpur International Airport",
                            "CUN": "Cancun International Airport",
                            "YUL": "Montreal Pierre Elliott Trudeau International Airport",
                            "RAK": "Mohammed V International Airport",
                            "AMS": "Amsterdam Airport Schiphol",
                            "LIS": "Lisbon Portela Airport",
                            "SJU": "San Juan Luis Munoz Marin International Airport",
                            "MAD": "Madrid-Barajas Airport",
                            "CPT": "Cape Town International Airport",
                            "YYZ": "Toronto Pearson International Airport",
                            "IST": "Istanbul Ataturk Airport",
                            "DXB": "Dubai International Airport",
                            "DWC": "Al Maktoum International Airport",
                            "YVR": "Vancouver International Airport",
                            "SGN": "Tan Son Nhat International Airport",
                            "CLT": "Charlotte International Airport",
                            "PHL": "Philadelphia International Airport",
                            "DAL": "Dallas Love Field",
                            "DCA": "Ronald Reagan Washington National Airport"}
